## NUMPY array and basics
Learning about NUMPY

import numpy as np

In [2]:
import numpy as np

### Creating array from list

In [4]:
arr_1d = np.array([1,2,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)


[1 2 4 5]
[[1 2 3]
 [4 5 6]]


 ### List vs numpy array

In [17]:
py_list = [1,2,3,4]
print("Multiplication of pylist",py_list * 2)
np_arr = np.array([1,2,3,4])#Element wise multiplication
print("Multiplication of array",np_arr * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time: ",time.time() - start)

start = time.time()
np_arr = np.arange(100000) * 2
print("Array operation time: ",time.time() - start)

Multiplication of pylist [1, 2, 3, 4, 1, 2, 3, 4]
Multiplication of array [2 4 6 8]
List operation time:  0.03984689712524414
Array operation time:  0.0002200603485107422


### Creating array from scratch

In [28]:
zeros = np.zeros((3,4))
print("Zeros array: \n",zeros)

ones = np.ones((3,4))
print("Ones array: \n",ones)

full = np.full((2,2),7)
print("Full array: \n",full)

random = np.random.random((2,3))
print("Random array: \n",random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n",sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.91198249 0.56807703 0.49106801]
 [0.40488685 0.12655602 0.53748508]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [36]:
vector = np.array([1,2,3,4])
print("Vector: \n",vector)

matrix = np.array([[1,2,3,4],[1,2,3,4]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3 4]
Matrix: 
 [[1 2 3 4]
 [1 2 3 4]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


### Array Properties

In [40]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("Dimention: ",arr.ndim)
print("Size: ",arr.size)
print("Data Type: ",arr.dtype)

Shape:  (2, 3)
Dimention:  2
Size:  6
Data Type:  int64


### Array Reshaping

In [49]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array \n",reshaped)

flattened = reshaped.flatten()
print("Flattened Array \n ",flattened)

# Ravel (returns view insted of copy)
raveled = reshaped.ravel()
print("Raveled Array \n", raveled)

# Transpose
transposed = reshaped.T
print("Transposed Array \n",transposed)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
