### NUMPY Array Operations

In [3]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5,6,7,8])
print("Basic slicing: ",arr[2:5])
print("With step: ",arr[1:8:2])
print("Negative index", arr[-3])

Basic slicing:  [3 4 5]
With step:  [2 4 6 8]
Negative index 6


In [16]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])
print("Specific Element: ",arr_2d[0,1])
print("Entire Row: ",arr_2d[1])
print("Entire Row: ",arr_2d[:,2])

Specific Element:  2
Entire Row:  [4 5 6]
Entire Row:  [3 6 9]


# Sorting

In [9]:
unsorted_arr = np.array([4,2,1,12,4,5])
print("Sorted array: ",np.sort(unsorted_arr))
arr_2d_unsorted = np.array([[2,1,3],[6,4,2],[8,3,2]])
print("Sorted 2d array: ",np.sort(arr_2d_unsorted,axis=1))

Sorted array:  [ 1  2  4  4  5 12]
Sorted 2d array:  [[1 2 3]
 [2 4 6]
 [2 3 8]]


## Filter

In [12]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ",even_numbers)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [14]:
mask = numbers > 5
print("Numbers greater theen five: ",numbers[mask])

Numbers greater theen five:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [18]:
indices = [0,2,3]
print("Indices: ",numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("np.where(): ",numbers[where_result])

Indices:  [1 3 4]
(array([5, 6, 7, 8, 9]),)
np.where():  [ 6  7  8  9 10]


In [24]:
condition_array = np.where(numbers > 5,numbers * 2,numbers)
# condition_array = np.where(numbers > 5,"true","false")
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])
print(a.shape == b.shape)

False


In [34]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(original)
print("with added row: \n",with_new_row)
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With added column: \n",with_new_col)


[[1 2]
 [3 4]]
with added row: 
 [[1 2]
 [3 4]
 [5 6]]
With added column: 
 [[1 2 7]
 [3 4 8]]


In [35]:
arr = np.array([1,2,3,4,5,6,7,8])
deleted = np.delete(arr, [2])
print("Original array: ",arr)
print("After deletion: ",deleted)

Original array:  [1 2 3 4 5 6 7 8]
After deletion:  [1 2 4 5 6 7 8]
